{
  "name": "ForceTry",
  "language": "swift",
  "description": "\n            Force tries should be avoided. If the code being wrapped happens to raise and exception, our application will crash.\n            Consider using a conditional try and handling the resulting optional, or wrapping the try statement in a do-catch block.\n        ",
  "example": "let x = try! someThrowingFunction() // violation, force trying\n\nlet x = try? someThrowingFunction() // no violation",
  "cwe": null,
  "cwe-description": null,
  "checker-language": "java",
  "loc": 0,
  "branches": 0,
  "apis": 0,
  "test": [
    {
      "description": "Good example #1",
      "expected-problems": 0,
      "expected-linenumbers": [],
      "code": "\nfunc a() throws {}\ndo {\n    try a()\n} catch {}\n        "
    },
    {
      "description": "Bad example #1",
      "expected-problems": 1,
      "expected-linenumbers": [],
      "code": "\nfunc a() throws {}\ntry! a()\n        "
    }
  ]
}