{
  "name": "Exception thrown in destructor",
  "description": "Throwing an exception from a destructor may cause immediate",
  "cwe": null,
  "cwe-description": null,
  "language": "cpp",
  "checker-language": "ql",
  "example": null,
  "loc": 45,
  "test": [],
  "branches": 0,
  "apis": 30
}