{
  "name": "Dangerous use of exception blocks.",
  "description": "When clearing the data in the catch block, you must be sure that the memory was allocated before the exception.",
  "cwe": "correctness",
  "cwe-description": null,
  "language": "cpp",
  "checker-language": "ql",
  "example": null,
  "loc": 166,
  "test": [],
  "branches": 7,
  "apis": 152
}