{
  "name": "AssertFalse",
  "language": "java",
  "description": "Assertions may be disabled at runtime and do not guarantee that execution will halt here; consider throwing an exception instead",
  "example": null,
  "cwe": null,
  "cwe-description": null,
  "checker-language": "java",
  "loc": 45,
  "branches": 2,
  "apis": 2,
  "test": [
    {
      "description": "negativeCase",
      "expected-problems": null,
      "expected-linenumbers": [
        33
      ],
      "code": "package com.google.errorprone.bugpatterns.testdata;\n\n            /**\n             * @author sebastian.h.monte@gmail.com (Sebastian Monte)\n             */\n            public class AssertFalseNegativeCases {\n\n              public void assertTrue() {\n                assert true;\n              }\n\n              public void assertFalseFromCondition() {\n                assert 0 == 1;\n              }\n            }\\"
    },
    {
      "description": "positiveCase",
      "expected-problems": null,
      "expected-linenumbers": [
        58
      ],
      "code": "package com.google.errorprone.bugpatterns.testdata;\n\n            /**\n             * @author sebastian.h.monte@gmail.com (Sebastian Monte)\n             */\n            public class AssertFalsePositiveCases {\n              public void assertFalse() {\n                // BUG: Diagnostic contains: throw new AssertionError()\n                assert false;\n              }\n            }\\"
    }
  ]
}