{
  "name": "ReachabilityFenceUsage",
  "language": "java",
  "description": "reachabilityFence should always be called inside a finally block",
  "example": null,
  "cwe": null,
  "cwe-description": null,
  "checker-language": "java",
  "loc": 60,
  "branches": 8,
  "apis": 1,
  "test": [
    {
      "description": "positive",
      "expected-problems": null,
      "expected-linenumbers": [
        31
      ],
      "code": "import java.lang.ref.Reference;\n\n            class Test {\n              public void run() {\n                // BUG: Diagnostic contains:\n                Reference.reachabilityFence(this);\n              }\n            }"
    },
    {
      "description": "positive_try",
      "expected-problems": null,
      "expected-linenumbers": [
        49
      ],
      "code": "import java.lang.ref.Reference;\n\n            class Test {\n              public void run() {\n                try {\n                  // BUG: Diagnostic contains:\n                  Reference.reachabilityFence(this);\n                } catch (Exception e) {\n                }\n              }\n            }"
    },
    {
      "description": "negative",
      "expected-problems": null,
      "expected-linenumbers": [
        70
      ],
      "code": "import java.lang.ref.Reference;\n\n            class Test {\n              public void run() {\n                try {\n                } finally {\n                  Reference.reachabilityFence(this);\n                }\n              }\n            }"
    }
  ]
}