{
  "name": "Accidental rethrow",
  "description": "When there is nothing to rethrow, attempting to rethrow an exception will terminate the program.",
  "cwe": null,
  "cwe-description": null,
  "language": "cpp",
  "checker-language": "ql",
  "example": null,
  "loc": 12,
  "test": [],
  "branches": 0,
  "apis": 10
}