{
  "name": "Catching by value",
  "description": "Catching an exception by value will create a copy of the thrown exception, thereby potentially slicing the original exception object.",
  "cwe": null,
  "cwe-description": null,
  "language": "cpp",
  "checker-language": "ql",
  "example": null,
  "loc": 5,
  "test": [],
  "branches": 0,
  "apis": 4
}